# Generated by Django 4.2 on 2025-09-12 16:45

import core.models.employeur
import core.models.user
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Analyste", "Analyste"),
                            ("Contrôleur", "Contrôleur"),
                            ("Admin", "Admin"),
                        ],
                        max_length=50,
                    ),
                ),
                ("avatar_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", core.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Anomalie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Effectif", "Effectif"),
                            ("Salaire", "Salaire"),
                            ("Déclaration", "Déclaration"),
                            ("Géographique", "Géographique"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "severite",
                    models.CharField(
                        choices=[
                            ("Faible", "Faible"),
                            ("Moyen", "Moyen"),
                            ("Élevé", "Élevé"),
                            ("Critique", "Critique"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("Nouvelle", "Nouvelle"),
                            ("En cours", "En cours"),
                            ("Résolue", "Résolue"),
                            ("Ignorée", "Ignorée"),
                        ],
                        default="Nouvelle",
                        max_length=20,
                    ),
                ),
                (
                    "valeur_attendue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "valeur_constatee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("date_detection", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("ml_model_version", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "db_table": "anomalies",
            },
        ),
        migrations.CreateModel(
            name="CroisementResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("total_matches", models.IntegerField(default=0)),
                ("cnps_only", models.IntegerField(default=0)),
                ("impot_only", models.IntegerField(default=0)),
                ("ecarts_significatifs", models.IntegerField(default=0)),
                ("tolerance_nom", models.FloatField(default=0.8)),
                ("seuil_ecart", models.IntegerField(default=5)),
            ],
            options={
                "db_table": "croisement_results",
            },
        ),
        migrations.CreateModel(
            name="Employeur",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("nom", models.CharField(max_length=255)),
                ("ville", models.CharField(blank=True, max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("Actif", "Actif"),
                            ("Inactif", "Inactif"),
                            ("Suspendu", "Suspendu"),
                            ("En contrôle", "En contrôle"),
                        ],
                        default="Actif",
                        max_length=50,
                    ),
                ),
                ("cnps_affilie", models.BooleanField(default=False)),
                (
                    "cnps_numero_affiliation",
                    models.CharField(blank=True, max_length=100),
                ),
                ("cnps_effectif_declare", models.IntegerField(default=0)),
                ("cnps_derniere_maj", models.DateTimeField(blank=True, null=True)),
                (
                    "impot_numero_contribuable",
                    models.CharField(blank=True, max_length=100),
                ),
                ("impot_effectif_declare", models.IntegerField(default=0)),
                (
                    "impot_chiffre_affaires",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("impot_derniere_maj", models.DateTimeField(blank=True, null=True)),
                (
                    "score_risque",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                (
                    "niveau_risque",
                    models.CharField(
                        choices=[
                            ("Faible", "Faible"),
                            ("Moyen", "Moyen"),
                            ("Élevé", "Élevé"),
                            ("Critique", "Critique"),
                        ],
                        default="Faible",
                        max_length=20,
                    ),
                ),
                ("last_control_date", models.DateTimeField(blank=True, null=True)),
                (
                    "search_vector",
                    core.models.employeur.SearchVectorField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "employeurs",
            },
        ),
        migrations.CreateModel(
            name="FileImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("filename", models.CharField(max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("CNPS", "CNPS"),
                            ("Impôts", "Impôts"),
                            ("Manuel", "Manuel"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "En attente"),
                            ("Processing", "En cours"),
                            ("Completed", "Terminé"),
                            ("Failed", "Échoué"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("total_records", models.IntegerField(default=0)),
                ("processed_records", models.IntegerField(default=0)),
                ("error_records", models.IntegerField(default=0)),
                ("file_path", models.CharField(max_length=500)),
                ("error_log", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "file_imports",
            },
        ),
        migrations.CreateModel(
            name="HistoriqueEffectif",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("annee", models.IntegerField()),
                ("mois", models.IntegerField()),
                ("effectif_cnps", models.IntegerField(default=0)),
                ("effectif_impots", models.IntegerField(default=0)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("CNPS", "CNPS"),
                            ("Impôts", "Impôts"),
                            ("Contrôle", "Contrôle"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "historique_effectifs",
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("nom", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
            ],
            options={
                "db_table": "regions",
            },
        ),
        migrations.CreateModel(
            name="Secteur",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("nom", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Secteur",
                "verbose_name_plural": "Secteurs",
                "db_table": "secteurs",
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_hash", models.CharField(db_index=True, max_length=255)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sessions",
            },
        ),
        migrations.AddIndex(
            model_name="secteur",
            index=models.Index(fields=["code"], name="secteurs_code_57a7ba_idx"),
        ),
        migrations.AddIndex(
            model_name="secteur",
            index=models.Index(fields=["nom"], name="secteurs_nom_737ccf_idx"),
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(fields=["code"], name="regions_code_aa1ecb_idx"),
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(fields=["nom"], name="regions_nom_addead_idx"),
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(
                fields=["latitude", "longitude"], name="regions_latitud_7a9ae1_idx"
            ),
        ),
        migrations.AddField(
            model_name="historiqueeffectif",
            name="employeur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historique_effectifs",
                to="core.employeur",
            ),
        ),
        migrations.AddField(
            model_name="fileimport",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeur",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employeurs",
                to="core.region",
            ),
        ),
        migrations.AddField(
            model_name="employeur",
            name="secteur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employeurs",
                to="core.secteur",
            ),
        ),
        migrations.AddField(
            model_name="croisementresult",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="croisementresult",
            name="import_cnps",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="croisements_cnps",
                to="core.fileimport",
            ),
        ),
        migrations.AddField(
            model_name="croisementresult",
            name="import_impot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="croisements_impots",
                to="core.fileimport",
            ),
        ),
        migrations.AddField(
            model_name="anomalie",
            name="employeur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anomalies",
                to="core.employeur",
            ),
        ),
        migrations.AddField(
            model_name="anomalie",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["user", "expires_at"], name="sessions_user_id_47ccf9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["token_hash"], name="sessions_token_h_e74511_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="historiqueeffectif",
            index=models.Index(
                fields=["employeur", "annee", "mois"],
                name="historique__employe_6b4899_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="historiqueeffectif",
            index=models.Index(
                fields=["annee", "mois"], name="historique__annee_e4ee1e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="historiqueeffectif",
            unique_together={("employeur", "annee", "mois", "source")},
        ),
        migrations.AddIndex(
            model_name="fileimport",
            index=models.Index(
                fields=["source", "status"], name="file_import_source_b4e36b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileimport",
            index=models.Index(
                fields=["created_at"], name="file_import_created_019962_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileimport",
            index=models.Index(
                fields=["uploaded_by"], name="file_import_uploade_2373d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeur",
            index=models.Index(fields=["nom"], name="employeurs_nom_a146bc_idx"),
        ),
        migrations.AddIndex(
            model_name="employeur",
            index=models.Index(
                fields=["secteur", "region"], name="employeurs_secteur_2732ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeur",
            index=models.Index(
                fields=["statut", "niveau_risque"], name="employeurs_statut_d20ff5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeur",
            index=models.Index(
                fields=["latitude", "longitude"], name="employeurs_latitud_355e64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="croisementresult",
            index=models.Index(
                fields=["created_at"], name="croisement__created_56483c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="croisementresult",
            index=models.Index(
                fields=["created_by"], name="croisement__created_b2f80c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomalie",
            index=models.Index(
                fields=["employeur", "statut"], name="anomalies_employe_3bd75f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomalie",
            index=models.Index(
                fields=["date_detection"], name="anomalies_date_de_68caeb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomalie",
            index=models.Index(
                fields=["type", "severite"], name="anomalies_type_5649a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="users_role_0ace22_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_active"], name="users_is_acti_847b48_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["date_joined"], name="users_date_jo_0c802f_idx"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(fields=("email",), name="uq_user_email"),
        ),
    ]
